image: terrestris/gitlab-runner-image:6.2.2.36-3@sha256:25b24b4cb89645ed365bc55ce3b54710f5c0093dd824b7eac59a7facdbab4388

variables:
  E2E_IMAGE_NAME: docker-public.terrestris.de/terrestris/shogun-gis-client-e2e-tests:latest

stages:
  - e2e

include:
  - project: 'ci-templates/playwright'
    ref: main
    file: '.gitlab-ci-template.yml'
