services:
  shogun-print:
    container_name: ${CONTAINER_NAME_PREFIX}-print
    image: camptocamp/mapfish_print:3.31.5
    volumes:
      - ./shogun-print/print-apps:/usr/local/tomcat/webapps/ROOT/print-apps:Z
  shogun-geoserver:
    container_name: ${CONTAINER_NAME_PREFIX}-geoserver
    image: docker.osgeo.org/geoserver:2.27.1
    environment:
      EXTRA_JAVA_OPTS: -Xms1g -Xmx2g -DGEOSERVER_CSRF_WHITELIST=${GEOSERVER_CSRF_WHITELIST} -Dgwc.context.suffix=gwc
      STABLE_EXTENSIONS: geofence-server-postgres,importer,sec-keycloak,web-resource
      RUN_UNPRIVILEGED: true
      RUN_WITH_USER_UID: ${UID}
      RUN_WITH_USER_GID: ${GID}
    depends_on:
      - shogun-postgis
    volumes:
      - ./shogun-geoserver/geoserver_data:/opt/geoserver_data/:Z
      - ./shogun-geoserver/additional_libs:/opt/additional_libs/:Z
      - ./shogun-geoserver/keystore/cacerts:/etc/ssl/certs/java/cacerts
  shogun-postgis:
    container_name: ${CONTAINER_NAME_PREFIX}-postgis
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./shogun-postgis/postgresql_data:/var/lib/postgresql/data:Z
      - ./shogun-postgis/init_data/01_init_keycloak.sql:/docker-entrypoint-initdb.d/01_init_keycloak.sql
      - ./shogun-postgis/init_data/02_init_geofence.sql:/docker-entrypoint-initdb.d/02_init_geofence.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 3s
      retries: 10
  shogun-keycloak:
    container_name: ${CONTAINER_NAME_PREFIX}-keycloak
    image: quay.io/keycloak/keycloak:25.0.6
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: shogun-postgis
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOST}
      KC_HOSTNAME_PATH: /auth
      KC_HTTP_RELATIVE_PATH: /auth
    depends_on:
      shogun-postgis:
        condition: service_healthy
    # Enable if you want to disable caching of the theme templates, e.g. while adjusting the custom shogun one.
    # command: ["start", "--proxy-headers", "xforwarded", "--http-enabled", "true", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false"]
    command: ["start", "--proxy-headers", "xforwarded", "--http-enabled", "true"]
    volumes:
      - ./shogun-keycloak/keystore/cacerts:/etc/pki/ca-trust/extracted/java/cacerts
      - ./shogun-keycloak/providers/event-listener-shogun-jar-with-dependencies.jar:/opt/keycloak/providers/event-listener-shogun-jar-with-dependencies.jar
      - ./shogun-keycloak/themes/shogun:/opt/keycloak/themes/shogun
  shogun-nginx:
    container_name: ${CONTAINER_NAME_PREFIX}-nginx
    image: nginx:1.28.0-alpine
    volumes:
      - ./shogun-admin/config/admin-client-config.js:/usr/share/nginx/html/admin/config/admin-client-config.js
      - ./shogun-admin/modelconfigs/:/usr/share/nginx/html/admin/modelconfigs/
      - ./shogun-client/config/gis-client-config.js:/usr/share/nginx/html/client/gis-client-config.js
    ports:
      - "80:80"
      - "443:443"
    environment:
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
    depends_on:
      - shogun-print
      - shogun-keycloak
      - shogun-geoserver
      - shogun-boot
      - shogun-client
      - shogun-gis-client-docs
      - shogun-admin
      - shogun-admin-client-docs
  shogun-client:
    container_name: ${CONTAINER_NAME_PREFIX}-gis-client
  shogun-client-plugins:
    container_name: ${CONTAINER_NAME_PREFIX}-gis-client-plugins
  shogun-admin:
    container_name: ${CONTAINER_NAME_PREFIX}-admin
  shogun-boot:
    container_name: ${CONTAINER_NAME_PREFIX}-boot
    environment:
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    depends_on:
      shogun-postgis:
        condition: service_healthy
    volumes:
      - ./shogun-boot/keystore/cacerts:/opt/java/openjdk/lib/security/cacerts
      - ./shogun-boot/application.yml:/config/application.yml
      - ./shogun-boot/log4j2.yml:/config/log4j2.yml
  # shogun-gs-interceptor:
  #   container_name: ${CONTAINER_NAME_PREFIX}-gs-interceptor
  #   environment:
  #     DB_USER: ${POSTGRES_USER}
  #     DB_PASSWORD: ${POSTGRES_PASSWORD}
  #     KEYCLOAK_HOST: ${KEYCLOAK_HOST}
  #     KEYCLOAK_USER: ${KEYCLOAK_USER}
  #     KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  #   volumes:
  #     - ./shogun-boot/keystore/cacerts:/etc/pki/ca-trust/extracted/java/cacerts
  #     - ./shogun-gs-interceptor/application.yml:/config/application.yml
  shogun-solr:
    container_name: ${CONTAINER_NAME_PREFIX}-solr
    image: solr:9.8.1
    volumes:
      - ./shogun-solr/solr_data:/var/solr
      - ./shogun-solr/jts.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jts.jar
  shogun-gis-client-docs:
    container_name: ${CONTAINER_NAME_PREFIX}-gis-client-docs
    image: docker-public.terrestris.de/terrestris/shogun-gis-client-docs:1.1.2
  shogun-admin-client-docs:
    container_name: ${CONTAINER_NAME_PREFIX}-admin-client-docs
    image: docker-public.terrestris.de/terrestris/shogun-admin-client-docs:1.1.2
