version: '3.7'
services:
  shogun-print:
    container_name: ${CONTAINER_NAME_PREFIX}-print
    image: camptocamp/mapfish_print:3.30.6
    volumes:
      - ./shogun-print/print-apps:/usr/local/tomcat/webapps/ROOT/print-apps:Z
  shogun-geoserver:
    container_name: ${CONTAINER_NAME_PREFIX}-geoserver
    environment:
      EXTRA_JAVA_OPTS: -Xms1g -Xmx2g -DGEOSERVER_CSRF_WHITELIST=${GEOSERVER_CSRF_WHITELIST} -Dgwc.context.suffix=gwc
      STABLE_EXTENSIONS: geofence-server,importer,sec-keycloak,web-resource
    volumes:
      - ./shogun-geoserver/geoserver_data:/opt/geoserver_data/:Z
      - ./shogun-geoserver/additional_libs:/opt/additional_libs/:Z
      - ./shogun-geoserver/keystore/cacerts:/etc/ssl/certs/java/cacerts
  shogun-postgis:
    container_name: ${CONTAINER_NAME_PREFIX}-postgis
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./shogun-postgis/postgresql_data:/var/lib/postgresql/data:Z
      - ./shogun-postgis/init_data/01_init_keycloak.sql:/docker-entrypoint-initdb.d/01_init_keycloak.sql
      - ./shogun-postgis/init_data/02_init_geofence.sql:/docker-entrypoint-initdb.d/02_init_geofence.sql
  shogun-keycloak:
    container_name: ${CONTAINER_NAME_PREFIX}-keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: shogun-postgis
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOST}
      KC_HOSTNAME_PATH: /auth
      KC_HTTP_RELATIVE_PATH: /auth
    command: ["start", "--proxy", "edge"]
    volumes:
     - ./shogun-keycloak/providers/event-listener-shogun-jar-with-dependencies.jar:/opt/keycloak/providers/event-listener-shogun-jar-with-dependencies.jar
    depends_on:
      - shogun-postgis
  shogun-nginx:
    container_name: ${CONTAINER_NAME_PREFIX}-nginx
    image: nginx:1.25.3-alpine
    volumes:
      - ./shogun-nginx/ssl/private/localhost.crt:/etc/nginx/ssl/private/localhost.crt
      - ./shogun-nginx/ssl/private/localhost.key:/etc/nginx/ssl/private/localhost.key
      - ./shogun-admin/config/admin-client-config.js:/usr/share/nginx/html/admin/config/admin-client-config.js
      - ./shogun-admin/modelconfigs/:/usr/share/nginx/html/admin/modelconfigs/
      - ./shogun-client/config/gis-client-config.js:/usr/share/nginx/html/client/gis-client-config.js
    ports:
      - "80:80"
      - "443:443"
    environment:
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
    depends_on:
      - shogun-keycloak
      - shogun-boot
      - shogun-geoserver
      - shogun-client
      - shogun-admin
      - shogun-print
  shogun-client:
    container_name: ${CONTAINER_NAME_PREFIX}-gis-client
  shogun-admin:
    container_name: ${CONTAINER_NAME_PREFIX}-admin
  shogun-boot:
    container_name: ${CONTAINER_NAME_PREFIX}-boot
    environment:
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - ./shogun-boot/keystore/cacerts:/opt/java/openjdk/lib/security/cacerts
      - ./shogun-boot/application.yml:/config/application.yml
      - ./shogun-boot/log4j2.yml:/config/log4j2.yml
    depends_on:
      - shogun-postgis
      - shogun-keycloak
  shogun-gs-interceptor:
    container_name: ${CONTAINER_NAME_PREFIX}-gs-interceptor
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_HOST: ${KEYCLOAK_HOST}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - ./shogun-boot/keystore/cacerts:/etc/pki/ca-trust/extracted/java/cacerts
      - ./shogun-gs-interceptor/application.yml:/config/application.yml
    depends_on:
      - shogun-postgis
      - shogun-keycloak
  shogun-solr:
    container_name: ${CONTAINER_NAME_PREFIX}-solr
    image: solr:9.4.0
    volumes:
      - ./shogun-solr/solr_data:/var/solr:RW
      - ./shogun-solr/jts.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jts.jar
